# Copyright (c) Pipin Fitriadi. All rights reserved.
# Licensed under the MIT License. See LICENSE in the project root for license information.

FROM mcr.microsoft.com/devcontainers/python:1-3.11-bullseye
RUN pip3 install ipykernel
