# Generated by Django 5.1.5 on 2025-01-31 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0002_alter_kursus_instruktur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiodataSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('tanggal_lahir', models.DateField()),
                ('nama_orang_tua', models.CharField(max_length=100)),
                ('telepon', models.CharField(max_length=15)),
                ('usia', models.IntegerField(blank=True, null=True)),
                ('siswa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biodata', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
