# Generated by Django 5.1.5 on 2025-01-31 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0003_biodatasiswa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siswa',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='biodatasiswa',
            name='siswa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='biodata', to='kursus.siswa'),
        ),
        migrations.AlterField(
            model_name='hasilkuis',
            name='feedback',
            field=models.CharField(choices=[('bagus', 'Bagus!'), ('coba_lagi', 'Coba lagi.')], default='coba_lagi', max_length=10),
        ),
        migrations.AlterField(
            model_name='hasilkuis',
            name='nilai',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hasilkuis',
            name='pendaftaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_kuis', to='kursus.pendaftaran'),
        ),
    ]
