# Generated by Django 5.1.5 on 2025-02-02 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0005_alter_biodatasiswa_tanggal_lahir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hasilkuis',
            name='jawaban',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Pilihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=200)),
                ('benar', models.BooleanField(default=False)),
                ('kuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kursus.kuis')),
            ],
        ),
        migrations.AddField(
            model_name='hasilkuis',
            name='pilihan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kursus.pilihan'),
        ),
    ]
