# Generated by Django 5.1.5 on 2025-02-02 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0006_alter_hasilkuis_jawaban_pilihan_hasilkuis_pilihan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hasilkuis',
            name='jawaban',
        ),
        migrations.AlterField(
            model_name='kuis',
            name='jawaban_benar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benar_untuk_kuis', to='kursus.pilihan'),
        ),
        migrations.AlterField(
            model_name='pilihan',
            name='kuis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihan', to='kursus.kuis'),
        ),
    ]
