# Generated by Django 5.1.5 on 2025-02-02 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0008_alter_pendaftaran_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kuis',
            name='jawaban_benar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='benar_untuk_kuis', to='kursus.pilihan'),
        ),
    ]
