# Generated by Django 5.1.5 on 2025-02-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kursus', '0011_materi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materi',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='materi',
            name='penjelasan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
